#!/bin/bash

NAME=gridengine
SCRIPTS_DIR=/home/ubuntu/config-tools
CONFIG_TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# create the GE cluster on the cloud platform
elasticluster start $NAME

first=yes
for host in `elasticluster list-nodes gridengine | grep "  -" | cut -d'-' -f2`; do
echo "installing packages on $host"

#since the home folder is shared among the nodes, we upload the script only once
if [ "$first" == "yes" ]; then
elasticluster sftp $NAME -n $host << EOF
mkdir $SCRIPTS_DIR
put $CONFIG_TOOLS_DIR/../nodes/node-install-packages.sh $SCRIPTS_DIR
EOF
first=no
fi

#install the packages on the node, create the scratch dir to use in the GE queue
elasticluster ssh $NAME -n $host << END
source $SCRIPTS_DIR/node-install-packages.sh
mkdir -p /home/ubuntu/scratch
END

done

#log in the frontend and change the shell used by GE from csh to bash
elasticluster ssh $NAME << FRONTEND
qconf -sq all.q > new_queue_config
sed -i 's#/bin/csh#/bin/bash#g' new_queue_config
sed -i 's#/tmp#/home/ubuntu/scratch#g' new_queue_config
sudo qconf -Mq new_queue_config
FRONTEND

echo "Cluster successfully created."

