#!/bin/bash

NAME=gridengine
CLUSTER_NAME=gridengine
. $HOME/.elasticluster/env

# create the GE cluster on the cloud platform
elasticluster start --name $CLUSTER_NAME $NAME 

#restart docker on each node. This is needed when the network is not ready on the node at docker installation time.
for host in `elasticluster list-nodes $CLUSTER_NAME | grep "  -" | cut -d'-' -f2`; do
echo "restarting docker on $host"
elasticluster ssh $CLUSTER_NAME -n $host << END
n=0
until [ "$n" -ge "5" ]
 do
 	sudo restart docker
 	output=`docker run artifacts/base:latest wget http://www.google.com 2>&1` 
 	if [[ "$output" == *"failed"* ]]; then
        	echo "Docker did not start properly! Trying to restart..."
        	n=$[$n+1]
        	sleep 3
 	else
        	echo "Docker network is working properly!"
 		break
 	fi                 
 done
END
done

if [ $? -eq 0 ]
then
  echo "Cluster ${CLUSTER_NAME} successfully created."
else
  echo "Could not create the cluster." >&2
fi

