#!/bin/bash

NAME=gridengine
CLUSTER_NAME=gridengine
. $HOME/.elasticluster/env

# create the GE cluster on the cloud platform
elasticluster start --name $CLUSTER_NAME $NAME 

if [ $? -eq 0 ]
then
  echo "Cluster ${CLUSTER_NAME} successfully created."
else
  echo "Could not create the cluster." >&2
fi

