---
- name: Grid Engine configuration Playbook
  hosts: gridengine_master 
  tasks:
  - name: Create target dir
    command: mkdir -p /home/ubuntu/config-tools
    become: yes
    become_user: ubuntu
  - name: Copy reconfigure script to node
    action: copy src="gridengine-queue/reconfigure.sh" dest="/home/ubuntu/config-tools/reconfigure.sh"
    become: yes
    become_user: ubuntu
  - name: Reconfigure Grid Engine queue
    shell: source /home/ubuntu/config-tools/reconfigure.sh
    args:
      executable: /bin/bash
    become: yes
    become_user: ubuntu
