---
- name: Grid Engine configuration Playbook
  hosts: gridengine_clients:gridengine_master 
  tasks:
  - name: Remove procs dir
    file: path=/home/ubuntu/procs state=absent
    become: yes
    become_user: ubuntu
    when: inventory_hostname in groups['gridengine_master']
  - name: Create procs dir
    file: path=/home/ubuntu/procs state=directory
    become: yes
    become_user: ubuntu
    when: inventory_hostname in groups['gridengine_master']
  - name: List processors per node
    shell: echo -n `hostname` ' ' >> $HOME/procs/`nproc`.proc 
    args:
      executable: /bin/bash
    become: yes
    become_user: ubuntu
    when: inventory_hostname in groups['gridengine_clients']
  - name: List processors per node
    shell: free -gt | tail -1 | awk '{print $2"g"}' >> $HOME/procs/`hostname`.mem
    args:
      executable: /bin/bash
    become: yes
    become_user: ubuntu
    when: inventory_hostname in groups['gridengine_clients']
  - name: Create script dir
    file: path=/home/ubuntu/config-tools state=directory
    become: yes
    become_user: ubuntu
    when: inventory_hostname in groups['gridengine_master']
  - name: Copy reconfigure script to node
    action: copy src="gridengine-queue/reconfigure.sh" dest="/home/ubuntu/config-tools/reconfigure.sh"
    become: yes
    become_user: ubuntu
    when: inventory_hostname in groups['gridengine_master']
  - name: Reconfigure Grid Engine queue
    shell: source /home/ubuntu/config-tools/reconfigure.sh
    args:
      executable: /bin/bash
    become: yes
    become_user: ubuntu
    when: inventory_hostname in groups['gridengine_master']
